### ISSUE TITLE
gujarati plugins not working

### ISSUE THREAD

**Issue by kodiokodi** [humla/canadanepal-xbmc#11]
Gujarati plugin not working on my amazon fire tv.
Rest all languages working.

**Comment by Gujal00** [comment]
In the last version,
Removed Gujarati Section
No Longer Available in the Website
What version of the plugin are you running?

**Comment by kodiokodi** [comment]
I am running 1.2.9
I set auto-update but its still 1.2.9

**Comment by Gujal00** [comment]
Looks like humla has not released the change yet. 1.2.9 was released 3 months ago and if you see the default.py here in github it is updated 2 months ago.
