### ISSUE TITLE
Einthusan Plugin not working

### ISSUE THREAD

**Issue by powerup87** [humla/canadanepal-xbmc#12]
Hi,
       Thank you for your awesome work words can't describe the work you did in creating one legendary plugin on kodi. Please update the plugin as its not working anymore. Thank you have a good one.

**Comment by sk280** [comment]
Hi there, 
+1, please update the plugin when possible.

I investigated this briefly and found that the pages are now returning 403 forbidden (from view source->URL played by jwPlayer).

Happy to help any way I can. 

Thanks

**Comment by powerup87** [comment]
Hello, 
          I tried the updates on all the device with your repository and also from tvaddons, and superrepo but still it wont play any movie. Thank you for your help.

**Comment by humla** [comment]
will have a look tonight

**Comment by powerup87** [comment]
thank you

**Comment by mhawaldar** [comment]
From the logs I see that following URL is being tried thru the plugin:

http://168.1.24.93/einthusancom/hot/D2978.mp4.m3u8?e=1470350962&md5=29CmJ-B-vAYmFoL5vFEivA

When I tried to trace the network calls from Chrome browser, I see following URL:

http://169.55.100.91/einthusancom/hot/D2978.mp4.ts?start=0&end=3600&e=1470356528&md5=8N9iT0pjL-cRuj5S8mynxg

I notice 2 extra parameters "start" and "end".

Hope this helps.

**Comment by humla** [comment]
Kodi should be able to play the m3u8 file. The m3u8 file has all the start and end time encoded inside it, if you open it in a text editor. 

The problem atm is that somehow I am able to play the m3u8 file I get via network tab in chrome dev window:
http://184.173.146.13/einthusancom/hot/D2986.mp4.m3u8?e=1470372244&md5=Vq0419znSkUYTXTvZlep2Q

But the same file I get from the plugin gives me an error:

http://50.97.49.68/einthusancom/hot/D2986.mp4.m3u8?e=1470372288&md5=W54NV636g5qdF15nHMpwCg

**Comment by Gujal00** [comment]
It is just header manipulation. I have done a fix and will do a pull request shortly

**Comment by kodiokodi** [comment]
Pl suggest what i need to do to update my FireTV ?

**Comment by Gujal00** [comment]
Please wait for Humla to review the pull request and release a new version.  You will get the update automatically

**Comment by modishit** [comment]
Hope humla pushes it soon.

**Comment by humla** [comment]
thanks, accepted the PR and pushed a new version from my phone at work. Hope it works now. Could you check and let me know.

**Comment by modishit** [comment]
Now it fails to install . Gives "Script error". Didn't update so i deleted the app and repo. but now can't install. Thanks.

**Comment by sk280** [comment]
Works perfectly. I did a manual update from the AddOn page.

**Comment by sk280** [comment]
New version is 1.3.0, works perfectly, Thank you Gujal00 and humla.

**Comment by sk280** [comment]
modishit, I suggest you uninstall the addon and install it again from scratch.

**Comment by modishit** [comment]
Apologies.. works perfectly. :-) Thanks Gujal00 and of course humla

**Comment by powerup87** [comment]
Thank you humla and gujal that was swift and great work. update works perfectly.
