### ISSUE TITLE
Something wrong with Einthusan 1.3.2 release

### ISSUE THREAD

**Issue by Gujal00** [humla/canadanepal-xbmc#16]
The release zip file is nowhere to be found, so the update is failing
Kodi log shows:
ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/humla/canadanepal-xbmc/master/repo/plugin.video.einthusan/plugin.video.einthusan-1.3.2.zip

**Comment by humla** [comment]
Forgot to add the zip file, added it now. Thanks for the heads up
