### ISSUE TITLE
Einthusan not working on Kodi 

### ISSUE THREAD

**Issue by janeshdev** [humla/canadanepal-xbmc#22]
Hi, I noticed that since yesterday einthusan is not working on kodi. Would you please let me know if you are working to fix that or not ?

**Comment by hjanjua** [comment]
Having same problem .. any fix to this ?

**Comment by cg8440** [comment]
Same problem here. Einthusan website itself has undergone a major revamp. So we need a fix.

**Comment by hjanjua** [comment]
Any update from the developer ?

**Comment by Gujal00** [comment]
Treat the add-on as dead for now. Read Humla's response
http://forum.kodi.tv/showthread.php?tid=146437&pid=2476283#pid2476283
