### ISSUE TITLE
Einthusan add-on for Kodi not working 

### ISSUE THREAD

**Issue by cg8440** [humla/canadanepal-xbmc#23]
After the major revamp on einthusan website two days ago, your add-on for Kodi is not working. Could you please provide a fix?

**Comment by Gujal00** [comment]
Treat the add-on as dead for now. Read Humla's response
http://forum.kodi.tv/showthread.php?tid=146437&pid=2476283#pid2476283

**Comment by humla** [comment]
Its fixed now
