### ISSUE TITLE
Update for Kodi

### ISSUE THREAD

**Issue by irfancharania** [humla/canadanepal-xbmc#3]
Latest change breaks add-on for older versions of XBMC/Kodi. Any chance of leaving addon.xml python version at 2.1.0?

Kodi already [supports it] (https://github.com/xbmc/xbmc/blob/master/addons/xbmc.python/addon.xml#L3) back to XBMC 12 Frodo

**Comment by humla** [comment]
Reverted it for now.
Thanks for letting me know.

**Comment by irfancharania** [comment]
appreciate it :)

**Comment by kathman** [comment]
Hi Humla, any work on the canadanepal addon? it's not currently working. would love to have it operational :-)

**Comment by humla** [comment]
Problem with Canadanepal is they keep on changing the web layout and which
website hosts their videos.

Nonetheless I have fixed the latest videos for now. Will try and fix the
other sections if I get some time.

**Comment by kathman** [comment]
Thanks man!
